services:
  postgres:
    image: postgres:16
    container_name: flowforge-postgres

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flowforge-network
  airflow-init:
    image: flowforge-airflow:dev
    container_name: flowforge-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@flowforge-postgres:5432/airflow
    depends_on:
      - postgres
    networks:
      - flowforge-network
    command: airflow db migrate
  airflow-webserver:
    image: flowforge-airflow:dev
    container_name: flowforge-webserver
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@flowforge-postgres:5432/airflow
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/logs:/opt/airflow/logs
    networks:
      - flowforge-network
    command: airflow api-server
  airflow-scheduler:
    image: flowforge-airflow:dev
    container_name: flowforge-scheduler
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@flowforge-postgres:5432/airflow
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/logs:/opt/airflow/logs
    networks:
      - flowforge-network
    command: airflow scheduler
  
volumes:
  postgres_data: 
networks:
  flowforge-network:
    name: flowforge-network
    driver: bridge